### ISSUE TITLE
Take the step's index in acount an reorder them when the index changes

### ISSUE THREAD

**Issue by Acedyn** [ArtFXDev/silex-front#65]
When new steps are inserted during the execution of an action, all the indexes of the following steps are shifted to insert the new steps in between. When an update is sent, the order of the steps must be recomputed using the index attribute to allow inserting steps in the middle of other steps.

**Comment by johhnry** [comment]
@Acedyn 

Currently I am rendering the steps like this:

```jsx
{Object.values(action.steps).filter(s => !s.hide).map(
  (step) => <StepItem key={step.uuid} step={step} />
)}
```

Do you mean that the order of the steps in the array is not the "real" order defined by the `index`?
If yes, I should probably sort them by index:

```ts
Object.values(action.steps).filter(s => !s.hide).sort((a, b) => a.index - b.index)...
```

**Comment by Acedyn** [comment]
Perfect
