### ISSUE TITLE
The boolean parameter does always display the default value

### ISSUE THREAD

**Issue by Acedyn** [ArtFXDev/silex-front#74]
Step to reproduce:
- go on silex-client
- git checkout conform-action
- rez build -i
- rez env silex_client -- silex action conform

-> the value of the parameter "Conform the sequence of the selected file" is actually false but shown to true
If you let the parameter at the default value, the value will actually be false

![image](https://user-images.githubusercontent.com/71290128/142169649-c76501e3-1575-41aa-8619-a75ce7d5ba12.png)

**Comment by johhnry** [comment]
Fixed with 74280eb3d8edf39277e1a4c7af1fc3d7ca3802c5
