### ISSUE TITLE
Create new parameters

### ISSUE THREAD

**Issue by Acedyn** [ArtFXDev/silex-front#76]
### Steps to reproduce:

```bash
git checkout parameter-update
rez env silex_client -- silex action tester
```

### Parameters
- [x] Text parameter, readonly text to display : {type: {name: "text"}, value: &lt;string&gt;}
- [x] Path parameter, update to handle more options: {type: {name: "Path", multiple: &lt;bool&gt;, extensions: &lt;string[]&gt;}, value: &lt;string&gt; | &lt;string&gt;[]}
- [x] Frame set parameter, like a string parameter with regex check {type: {name: "FrameSet"}, value: &lt;string>} (see FrameSet docstring at https://github.com/justinfx/fileseq/blob/master/src/fileseq/frameset.py)

### Optional sugar (These parameters are used only in hidden parameters for now)
- [ ] Warn the user when he press "continue" and a value is still null
- [x] List parameter, this parameter is a list of any parameter, it would be similar to the multiparm folders in houdini:
{type: {name: "list", itemtype: {&lt;the-type-of-the-parameter-in-the-list&gt;}}, value: &lt;any[]&gt;}

**Comment by GuillaumeRoeder** [comment]
for path parameter, add access to directory

**Comment by johhnry** [comment]
For the directory support: [`webkitdirectory`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file#webkitdirectory)

Also:

- [ ] Fix multiple select not displaying default value
