### ISSUE TITLE
Work with diff for performance boost in big actions

### ISSUE THREAD

**Issue by Acedyn** [ArtFXDev/silex-front#77]
### Steps to reproduce:

```bash
git checkout optimisation
rez env silex_client -- silex action stress-test
```

### Problem
This action iterate over the tester action 40 times. It ends up with a huge action which is supposed to mimic the size of a conform action on a big scene.
The more steps there is, the slower it gets. If we work only with diff, the action can have any size and update time will not grow (or a little)

**Comment by johhnry** [comment]
Fixed in #78
